[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://abhishekn.dev"
  NEXT_PUBLIC_SUPABASE_URL = "https://edgjmuuiivyqcrtajvtf.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_U-uRM9KLmalBcOsZSNQrCQ_tAsLFTDd"
  NEXT_PUBLIC_HTRACKER_ALLOWED_EMAIL = "abisanju143@gmail.com"
